WITH
SCE_PER_AREA_ORI AS (
    SELECT
    *
    FROM(
        SELECT
            SCENARIO_PERIODO_AREA.COD_SCENARIO AS COD_SCENARIO
            , SCENARIO.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO_ORIGINARIO
            , PERC_INTERESSENZA
            , PERC_PROPORZIONALITA
            , TIPO_CONSOLIDAMENTO
            , TIPO_DECONSOLIDAMENTO
            , SCENARIO.COD_AZI_CAPOGRUPPO AS COD_AZI_CTP
            , SCENARIO_PERIODO_AREA.COD_PERIODO
            , SCENARIO_PERIODO_AREA.COD_AZIENDA
        FROM
            SCENARIO_PERIODO_AREA
        LEFT JOIN
            SCENARIO
        ON
            SCENARIO_PERIODO_AREA.COD_SCENARIO = SCENARIO.COD_SCENARIO
    )
    WHERE
        COD_SCENARIO = {PAR_0030}
        AND COD_PERIODO = {PAR_0020}
),

STOCK_RATE AS (
    SELECT
    *
    FROM(
        SELECT 
            SCENARIO.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO_ORIGINARIO,
            STOCK_RATE_DATASET.SCENARIO AS COD_SCENARIO,
            STOCK_RATE_DATASET.OWNING_COMPANY,
            STOCK_RATE_DATASET.OWNED_COMPANY,
            STOCK_RATE_DATASET.PERIOD AS COD_PERIODO,
            EQUITY_RATIO,
            INTERACTION_FLAG
        FROM
            {AW|001|000020|TYP_02|$|$|$|$} AS STOCK_RATE_DATASET
        LEFT JOIN
            SCENARIO
        ON
            STOCK_RATE_DATASET.SCENARIO = SCENARIO.COD_SCENARIO
    )
    WHERE
        COD_SCENARIO = {PAR_0030}
        AND COD_PERIODO = {PAR_0020}
),

OWNER_RATE AS (
    SELECT
    *
    FROM(
        SELECT
            SCENARIO.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO_ORIGINARIO,
            SCENARIO.COD_AZI_CAPOGRUPPO,
            OWNER_RATE_DATASET.SCENARIO,
            OWNER_RATE_DATASET.ENTITY,
            OWNER_RATE_DATASET.PERIOD,
            OWNER_RATE_DATASET.SHARE_RATIO,
            OWNER_RATE_DATASET.CNSL_METHOD,
            OWNER_RATE_DATASET.EX_CNSL_METHOD
        FROM
            {AW|001|000018|TYP_01|$|$|$|$} AS OWNER_RATE_DATASET
        LEFT JOIN
            SCENARIO
        ON
            OWNER_RATE_DATASET.SCENARIO = SCENARIO.COD_SCENARIO
        WHERE
            OWNER_RATE_DATASET.SHARE_RATIO <> -1
    )
    WHERE
        SCENARIO = {PAR_0030}
        AND PERIOD = {PAR_0020}
),

CONS_SCO_CHK_EXISTING AS (
    SELECT
        OID,
        COD_SCENARIO,
        COD_PERIODO,
        COD_AZIENDA,
        COD_AZI_CTP,
        COD_CATEGORIA,
        COD_DEST3,
        COD_DEST4,
        COD_DEST5,
        COD_SCENARIO_AW,
        INT_001,
        INT_002,
        INT_003,
        INT_004,
        INT_005,
        DECIMAL_001,
        DECIMAL_002,
        DECIMAL_003,
        DECIMAL_004,
        DECIMAL_005,
        DECIMAL_006,
        DECIMAL_007,
        TEXT_001,
        TEXT_002,
        TEXT_003,
        TEXT_004,
        TEXT_005,
        TEXT_006,
        TEXT_007,
        TEXT_008,
        TEXT_009,
        TEXT_010,
        TEXT_011,
        TEXT_012,
        TEXT_013
    FROM
        {AW|001|000060|TPL001|{PROCESS}|{PAR_0010}|{PAR_0020}|$} AS CONS_SCO_CHK_DATASET
    WHERE
        COD_SCENARIO_AW = {PAR_0030}
),

CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE AS (

    SELECT
        SCE_PER_AREA_ORI.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO,
        SCE_PER_AREA_ORI.COD_PERIODO AS COD_PERIODO,
        SCE_PER_AREA_ORI.COD_AZIENDA AS COD_AZIENDA,
        SCE_PER_AREA_ORI.COD_AZI_CTP AS COD_AZI_CTP,
        NULL AS COD_CATEGORIA,
        NULL AS COD_DEST3,
        NULL AS COD_DEST4,
        NULL AS COD_DEST5,
        SCE_PER_AREA_ORI.COD_SCENARIO AS COD_SCENARIO_AW,
        NULL AS INT_001,
        NULL AS INT_002,
        NULL AS INT_003,
        NULL AS INT_004,
        NULL AS INT_005,
        STOCK_RATE.EQUITY_RATIO/100 AS DECIMAL_001,
        NULL AS DECIMAL_002,
        NULL AS DECIMAL_003,
        NULL AS DECIMAL_004,
        NULL AS DECIMAL_005,
        NULL AS DECIMAL_006,
        SCE_PER_AREA_ORI.PERC_INTERESSENZA/100 AS DECIMAL_007,
        NULL AS TEXT_001,
        NULL AS TEXT_002,
        SCE_PER_AREA_ORI.TIPO_CONSOLIDAMENTO AS TEXT_003,
        NULL AS TEXT_004,
        NULL AS TEXT_005,
        NULL AS TEXT_006,
        NULL AS TEXT_007,
        NULL AS TEXT_008,
        NULL AS TEXT_009,
        NULL AS TEXT_010,
        NULL AS TEXT_011,
        NULL AS TEXT_012,
        NULL AS TEXT_013
    FROM 
        SCE_PER_AREA_ORI
    LEFT JOIN
        STOCK_RATE
    ON
        STOCK_RATE.COD_SCENARIO_ORIGINARIO = SCE_PER_AREA_ORI.COD_SCENARIO_ORIGINARIO
        AND STOCK_RATE.COD_PERIODO = SCE_PER_AREA_ORI.COD_PERIODO
        AND STOCK_RATE.OWNED_COMPANY = SCE_PER_AREA_ORI.COD_AZIENDA 
        AND STOCK_RATE.OWNING_COMPANY = SCE_PER_AREA_ORI.COD_AZI_CTP
        AND STOCK_RATE.COD_SCENARIO = SCE_PER_AREA_ORI.COD_SCENARIO
    UNION
    SELECT
        STOCK_RATE.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO,
        STOCK_RATE.COD_PERIODO AS COD_PERIODO,
        STOCK_RATE.OWNED_COMPANY AS COD_AZIENDA,
        STOCK_RATE.OWNING_COMPANY AS COD_AZI_CTP,
        NULL AS COD_CATEGORIA,
        NULL AS COD_DEST3,
        NULL AS COD_DEST4,
        NULL AS COD_DEST5,
        STOCK_RATE.COD_SCENARIO AS COD_SCENARIO_AW,
        NULL AS INT_001,
        NULL AS INT_002,
        NULL AS INT_003,
        NULL AS INT_004,
        NULL AS INT_005,
        STOCK_RATE.EQUITY_RATIO/100 AS DECIMAL_001,
        NULL AS DECIMAL_002,
        NULL AS DECIMAL_003,
        NULL AS DECIMAL_004,
        NULL AS DECIMAL_005,
        NULL AS DECIMAL_006,
        NULL AS DECIMAL_007,
        NULL AS TEXT_001,
        NULL AS TEXT_002,
        NULL AS TEXT_003,
        NULL AS TEXT_004,
        NULL AS TEXT_005,
        NULL AS TEXT_006,
        NULL AS TEXT_007,
        NULL AS TEXT_008,
        NULL AS TEXT_009,
        NULL AS TEXT_010,
        NULL AS TEXT_011,
        NULL AS TEXT_012,
        NULL AS TEXT_013
    FROM 
        STOCK_RATE
    WHERE STOCK_RATE.OWNING_COMPANY NOT IN(SELECT COD_AZI_CTP FROM SCE_PER_AREA_ORI)
),

CONS_SCO_CHK_SCE_OWNER_RATE AS (
    SELECT
        NEWID() AS OID,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_SCENARIO,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_PERIODO,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_AZIENDA,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_AZI_CTP,
        NULL AS COD_CATEGORIA,
        NULL AS COD_DEST3,
        NULL AS COD_DEST4,
        NULL AS COD_DEST5,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_SCENARIO_AW,
        NULL AS INT_001,
        NULL AS INT_002,
        NULL AS INT_003,
        NULL AS INT_004,
        NULL AS INT_005,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.DECIMAL_001,
        NULL AS DECIMAL_002,
        NULL AS DECIMAL_003,
        OWNER_RATE.SHARE_RATIO/100 AS DECIMAL_004,
        NULL AS DECIMAL_005,
        NULL AS DECIMAL_006,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.DECIMAL_007,
        NULL AS TEXT_001,
        NULL AS TEXT_002,
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.TEXT_003,
        NULL AS TEXT_004,
        NULL AS TEXT_005,
        NULL AS TEXT_006,
        NULL AS TEXT_007,
        NULL AS TEXT_008,
        NULL AS TEXT_009,
        NULL AS TEXT_010,
        NULL AS TEXT_011,
        OWNER_RATE.EX_CNSL_METHOD AS TEXT_012,
        NULL AS TEXT_013
    FROM
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE
    LEFT JOIN
        OWNER_RATE
    ON
        CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_SCENARIO = OWNER_RATE.COD_SCENARIO_ORIGINARIO
        AND CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_PERIODO = OWNER_RATE.PERIOD
        AND CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_AZIENDA = OWNER_RATE.ENTITY
        AND CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_AZI_CTP = OWNER_RATE.COD_AZI_CAPOGRUPPO
        AND CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_SCENARIO_AW = OWNER_RATE.SCENARIO
        AND CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_SCENARIO = {PAR_0010}
        AND CONS_SCO_CHK_SCE_PER_AREA_STOCK_RATE.COD_PERIODO = {PAR_0020}
),

CONS_SCO_CHK_SCE_BEFORE_EXCLUDING AS (
    SELECT
        CONS_SCO_CHK_SCE_OWNER_RATE.OID,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_SCENARIO,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_PERIODO,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_AZIENDA,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_AZI_CTP,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_CATEGORIA,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_DEST3,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_DEST4,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_DEST5,
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_SCENARIO_AW,
        CONS_SCO_CHK_SCE_OWNER_RATE.INT_001,
        CONS_SCO_CHK_SCE_OWNER_RATE.INT_002,
        CONS_SCO_CHK_SCE_OWNER_RATE.INT_003,
        CONS_SCO_CHK_SCE_OWNER_RATE.INT_004,
        CONS_SCO_CHK_SCE_OWNER_RATE.INT_005,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_001,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_002,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_003,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_004,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_005,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_006,
        CONS_SCO_CHK_SCE_OWNER_RATE.DECIMAL_007,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_001,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_002,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_003,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_004,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_005,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_006,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_007,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_008,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_009,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_010,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_011,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_012,
        CONS_SCO_CHK_SCE_OWNER_RATE.TEXT_013,
        CONS_SCO_CHK_EXISTING.COD_AZIENDA AS COD_AZIENDA_EXISTING,
        CONS_SCO_CHK_EXISTING.COD_AZI_CTP AS COD_AZI_CTP_EXISTING
    FROM
        CONS_SCO_CHK_SCE_OWNER_RATE
    LEFT JOIN
        CONS_SCO_CHK_EXISTING
    ON
        CONS_SCO_CHK_SCE_OWNER_RATE.COD_SCENARIO = CONS_SCO_CHK_EXISTING.COD_SCENARIO
        AND CONS_SCO_CHK_SCE_OWNER_RATE.COD_PERIODO = CONS_SCO_CHK_EXISTING.COD_PERIODO
        AND CONS_SCO_CHK_SCE_OWNER_RATE.COD_SCENARIO_AW = CONS_SCO_CHK_EXISTING.COD_SCENARIO_AW
        AND CONS_SCO_CHK_SCE_OWNER_RATE.COD_AZIENDA = CONS_SCO_CHK_EXISTING.COD_AZIENDA
        AND CONS_SCO_CHK_SCE_OWNER_RATE.COD_AZI_CTP = CONS_SCO_CHK_EXISTING.COD_AZI_CTP
)

SELECT
    OID,
    {PAR_0010} AS COD_SCENARIO,
    {PAR_0020} AS COD_PERIODO,
    COD_AZIENDA,
    COD_AZI_CTP,
    COD_CATEGORIA,
    COD_DEST3,
    COD_DEST4,
    COD_DEST5,
    {PAR_0030} AS COD_SCENARIO_AW,
    INT_001,
    INT_002,
    INT_003,
    INT_004,
    INT_005,
    DECIMAL_001,
    DECIMAL_002,
    DECIMAL_003,
    DECIMAL_004,
    DECIMAL_005,
    DECIMAL_006,
    DECIMAL_007,
    TEXT_001,
    TEXT_002,
    TEXT_003,
    TEXT_004,
    TEXT_005,
    TEXT_006,
    TEXT_007,
    TEXT_008,
    TEXT_009,
    TEXT_010,
    TEXT_011,
    TEXT_012,
    TEXT_013,
    TO_CHAR(NOW(), 'yyyy/mm/dd hh24:mi:ss') AS DATEUPD,
    {USER} AS USERUPD,
    {MAP} || '_' ||  {IMP} AS PROVENIENZA
FROM
    CONS_SCO_CHK_SCE_BEFORE_EXCLUDING
WHERE
    COD_AZIENDA_EXISTING IS NULL
    AND COD_AZI_CTP_EXISTING IS NULL