WITH
SCE_PER_AREA_ORI AS (
    SELECT
        SCENARIO_PERIODO_AREA.COD_SCENARIO AS COD_SCENARIO
        , SCENARIO.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO_ORIGINARIO
        , PERC_INTERESSENZA
        , PERC_PROPORZIONALITA
        , TIPO_CONSOLIDAMENTO
        , TIPO_DECONSOLIDAMENTO
        , SCENARIO.COD_AZI_CAPOGRUPPO AS COD_AZI_CTP
        , SCENARIO_PERIODO_AREA.COD_PERIODO
        , SCENARIO_PERIODO_AREA.COD_AZIENDA
    FROM
        SCENARIO_PERIODO_AREA
    LEFT JOIN
        SCENARIO
    ON
        SCENARIO_PERIODO_AREA.COD_SCENARIO = SCENARIO.COD_SCENARIO
),

CONS_SCO_CHK_DEC7 AS (
    SELECT
        OID,
        SCE_PER_AREA_ORI.COD_SCENARIO AS COD_SCENARIO,
        SCE_PER_AREA_ORI.COD_PERIODO,
        SCE_PER_AREA_ORI.COD_AZIENDA,
        SCE_PER_AREA_ORI.COD_AZI_CTP AS COD_AZI_CTP,
        CONS_SCO_CHK_DATASET.COD_CATEGORIA,
        COD_DEST3,
        COD_DEST4,
        COD_DEST5,
        CONS_SCO_CHK_DATASET.COD_SCENARIO_AW,
        INT_001,
        INT_002,
        INT_003,
        INT_004,
        INT_005,
        DECIMAL_001,
        DECIMAL_002,
        DECIMAL_003,
        DECIMAL_004,
        DECIMAL_005,
        DECIMAL_006,
        SCE_PER_AREA_ORI.PERC_INTERESSENZA/100 AS DECIMAL_007,
        TEXT_001,
        TEXT_002,
        SCE_PER_AREA_ORI.TIPO_CONSOLIDAMENTO AS TEXT_003,
        TEXT_004,
        TEXT_005,
        TEXT_006,
        TEXT_007,
        TEXT_008,
        TEXT_009,
        TEXT_010,
        TEXT_011,
        TEXT_012,
        TEXT_013
    FROM 
         SCE_PER_AREA_ORI
    LEFT JOIN
         {AW|001|000060|TPL001|{PROCESS}|{PAR_0010}|{PAR_0020}|$} AS CONS_SCO_CHK_DATASET
    ON
        CONS_SCO_CHK_DATASET.COD_SCENARIO = SCE_PER_AREA_ORI.COD_SCENARIO_ORIGINARIO
        AND CONS_SCO_CHK_DATASET.COD_PERIODO = SCE_PER_AREA_ORI.COD_PERIODO
        AND CONS_SCO_CHK_DATASET.COD_AZIENDA = SCE_PER_AREA_ORI.COD_AZIENDA
        AND CONS_SCO_CHK_DATASET.COD_AZI_CTP = SCE_PER_AREA_ORI.COD_AZI_CTP 
        AND CONS_SCO_CHK_DATASET.COD_SCENARIO_AW = SCE_PER_AREA_ORI.COD_SCENARIO
    WHERE
        CONS_SCO_CHK_DATASET.COD_SCENARIO_AW = {PAR_0030}
        
),

STOCK_RATE AS (
    SELECT 
        SCENARIO.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO_ORIGINARIO,
        STOCK_RATE_DATASET.SCENARIO AS COD_SCENARIO,
        STOCK_RATE_DATASET.OWNING_COMPANY,
        STOCK_RATE_DATASET.OWNED_COMPANY,
        STOCK_RATE_DATASET.PERIOD AS COD_PERIODO,
        EQUITY_RATIO,
        INTERACTION_FLAG
    FROM
        {AW|001|000020|TYP_02|$|$|$|$} AS STOCK_RATE_DATASET
    LEFT JOIN
        SCENARIO
    ON
        STOCK_RATE_DATASET.SCENARIO = SCENARIO.COD_SCENARIO
    WHERE
        SCENARIO = {PAR_0030}
        AND PERIOD = {PAR_0020}
),

CONS_SCO_CHK_DEC1 AS (
    SELECT
        OID,
        CONS_SCO_CHK_DEC7.COD_SCENARIO AS COD_SCENARIO,
        CONS_SCO_CHK_DEC7.COD_PERIODO,
        CONS_SCO_CHK_DEC7.COD_AZIENDA,
        CONS_SCO_CHK_DEC7.COD_AZI_CTP,
        CONS_SCO_CHK_DEC7.COD_CATEGORIA,
        CONS_SCO_CHK_DEC7.COD_DEST3,
        CONS_SCO_CHK_DEC7.COD_DEST4,
        CONS_SCO_CHK_DEC7.COD_DEST5,
        CONS_SCO_CHK_DEC7.COD_SCENARIO_AW,
        INT_001,
        INT_002,
        INT_003,
        INT_004,
        INT_005,
        EQUITY_RATIO/100 AS DECIMAL_001,
        DECIMAL_002,
        DECIMAL_003,
        DECIMAL_004,
        DECIMAL_005,
        DECIMAL_006,
        DECIMAL_007,
        TEXT_001,
        TEXT_002,
        TEXT_003,
        TEXT_004,
        TEXT_005,
        TEXT_006,
        TEXT_007,
        TEXT_008,
        TEXT_009,
        TEXT_010,
        TEXT_011,
        TEXT_012,
        TEXT_013
    FROM
        CONS_SCO_CHK_DEC7
    LEFT JOIN
        STOCK_RATE
    ON
        CONS_SCO_CHK_DEC7.COD_SCENARIO = STOCK_RATE.COD_SCENARIO_ORIGINARIO
        AND CONS_SCO_CHK_DEC7.COD_PERIODO = STOCK_RATE.COD_PERIODO
        AND CONS_SCO_CHK_DEC7.COD_AZIENDA = STOCK_RATE.OWNED_COMPANY
        AND CONS_SCO_CHK_DEC7.COD_AZI_CTP = STOCK_RATE.OWNING_COMPANY
        AND CONS_SCO_CHK_DEC7.COD_SCENARIO_AW = {PAR_0030}
),

OWNER_RATE AS (
    SELECT
        SCENARIO.COD_SCENARIO_ORIGINARIO AS COD_SCENARIO_ORIGINARIO,
        SCENARIO.COD_AZI_CAPOGRUPPO,
        OWNER_RATE_DATASET.SCENARIO,
        OWNER_RATE_DATASET.ENTITY,
        OWNER_RATE_DATASET.PERIOD,
        OWNER_RATE_DATASET.SHARE_RATIO,
        OWNER_RATE_DATASET.CNSL_METHOD,
        OWNER_RATE_DATASET.EX_CNSL_METHOD
    FROM
        {AW|001|000018|TYP_01|$|$|$|$} AS OWNER_RATE_DATASET
    LEFT JOIN
        SCENARIO
    ON
        OWNER_RATE_DATASET.SCENARIO = SCENARIO.COD_SCENARIO
        WHERE
            OWNER_RATE_DATASET.SHARE_RATIO <> -1
),

CONS_SCO_CHK_OWNER_RATE AS (
    SELECT
        CONS_SCO_CHK_DEC1.OID AS OID, 
        CONS_SCO_CHK_DEC1.COD_SCENARIO AS COD_SCENARIO,
        CONS_SCO_CHK_DEC1.COD_PERIODO,
        CONS_SCO_CHK_DEC1.COD_AZIENDA,
        CONS_SCO_CHK_DEC1.COD_AZI_CTP,
        CONS_SCO_CHK_DEC1.COD_CATEGORIA,
        CONS_SCO_CHK_DEC1.COD_DEST3,
        CONS_SCO_CHK_DEC1.COD_DEST4,
        CONS_SCO_CHK_DEC1.COD_DEST5,
        CONS_SCO_CHK_DEC1.COD_SCENARIO_AW,
        INT_001,
        INT_002,
        INT_003,
        INT_004,
        INT_005,
        DECIMAL_001,
        DECIMAL_002,
        DECIMAL_003,
        OWNER_RATE.SHARE_RATIO/100 AS DECIMAL_004,
        DECIMAL_005,
        DECIMAL_006,
        DECIMAL_007,
        TEXT_001,
        TEXT_002,
        TEXT_003,
        TEXT_004,
        TEXT_005,
        TEXT_006,
        TEXT_007,
        TEXT_008,
        TEXT_009,
        TEXT_010,
        TEXT_011,
        OWNER_RATE.EX_CNSL_METHOD AS TEXT_012,
        TEXT_013
    FROM
        CONS_SCO_CHK_DEC1
    LEFT JOIN
        OWNER_RATE
    ON
        CONS_SCO_CHK_DEC1.COD_SCENARIO = OWNER_RATE.COD_SCENARIO_ORIGINARIO
        AND CONS_SCO_CHK_DEC1.COD_PERIODO = OWNER_RATE.PERIOD
        AND CONS_SCO_CHK_DEC1.COD_AZIENDA = OWNER_RATE.ENTITY
        AND CONS_SCO_CHK_DEC1.COD_AZI_CTP = OWNER_RATE.COD_AZI_CAPOGRUPPO
        AND CONS_SCO_CHK_DEC1.COD_SCENARIO_AW = OWNER_RATE.SCENARIO
        AND CONS_SCO_CHK_DEC1.COD_SCENARIO_AW = {PAR_0030}
)

SELECT
    CONS_SCO_CHK_OWNER_RATE.OID AS OID,
    CONS_SCO_CHK_OWNER_RATE.COD_SCENARIO AS COD_SCENARIO,
    CONS_SCO_CHK_OWNER_RATE.COD_PERIODO,
    CONS_SCO_CHK_OWNER_RATE.COD_AZIENDA,
    CONS_SCO_CHK_OWNER_RATE.COD_AZI_CTP,
    CONS_SCO_CHK_OWNER_RATE.COD_CATEGORIA,
    CONS_SCO_CHK_OWNER_RATE.COD_DEST3,
    CONS_SCO_CHK_OWNER_RATE.COD_DEST4,
    CONS_SCO_CHK_OWNER_RATE.COD_DEST5,
    CONS_SCO_CHK_OWNER_RATE.COD_SCENARIO_AW,
    INT_001,
    INT_002,
    INT_003,
    INT_004,
    INT_005,
    DECIMAL_001,
    DECIMAL_002,
    DECIMAL_003,
    DECIMAL_004,
    DECIMAL_005,
    DECIMAL_006,
    DECIMAL_007,
    TEXT_001,
    TEXT_002,
    TEXT_003,
    TEXT_004,
    TEXT_005,
    TEXT_006,
    TEXT_007,
    TEXT_008,
    TEXT_009,
    TEXT_010,
    TEXT_011,
    TEXT_012,
    TEXT_013,
    TO_CHAR(NOW(), 'yyyy/mm/dd hh24:mi:ss') AS DATEUPD,
    {USER} AS USERUPD,
    {MAP} || '_' ||  {IMP} AS PROVENIENZA
FROM
    CONS_SCO_CHK_OWNER_RATE